services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - "${GOOGLE_CREDENTIALS_PATH}:/run/secrets/paperstore-credentials.json:ro"
      - ./backend/src:/app/src
      - ./frontend:/frontend
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: "1"
